# Generated by Django 3.0.6 on 2020-06-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='room_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
