# Generated by Django 3.0.6 on 2020-06-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_votes_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='A',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='votes',
            name='B',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='votes',
            name='X',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='votes',
            name='Y',
            field=models.IntegerField(default=0),
        ),
    ]
